name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: asallin/website2@master
      env:
        HUGO_VERSION: 0.102.3
        TARGET_REPO: asallin/asallin.github.io
        TOKEN: ${{ secrets.TOKENPAT }}
